version: '3'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app
      - ./.env:/.env
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    image: mongodb/mongodb-community-server:8.0-ubi8
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
